package scripts.jjsgoptokenexchanger;

public enum ExchangeState {
	WALK_TO_GUILD_ENTRANCE, ENTER_GUILD_ENTRANCE,
	WALK_TO_ELRISS, INTERACT_WITH_ELRISS, BUY_TALISMANS,
	WALK_TO_GUILD_EXIT, ENTER_GUILD_EXIT, WALK_TO_BANK,
	DEPOSIT_ITEMS, GUI;
}
