package org.obduro.agilityarena.utils;

public enum Obstacle {
	PLANK, LOW_WALL, BALANCING_ROPE, LOG_BALANCE, 
	MONKEY_BARS, BALANCING_LEDGE, PILLARS, ROPE_SWING, 
	BLADE, FLOOR_SPIKES, PRESSURE_PAD, HAND_HOLDS, 
	SPINNING_BLADE, STAT_DARTS, PLATFORM, EMPTY;
}