package scripts;

public enum JJsFlaxState {
	SELECT_FLAX, TYPE_AMOUNT, CRAFTING, WHEEL_TO_STAIRS,
	CLIMB_STAIRS, STAIRS_TO_BANK, OPEN_BANK, 
	DEPOSIT_BOW_STRING, WITHDRAW_FLAX, BANK_TO_STAIRS, 
	STAIRS_TO_WHEEL, OPEN_DOOR, USE_SPIN_WHEEL,
	WALK_TO_DOOR, DEPOSIT_JUNK, DEATH_WALK;
}
